### ISSUE TITLE
Make Install Error

### ISSUE THREAD

**Issue by robson-lopes** [litespeedtech/lsmcd#1]
root@lsmcd:~/lsmcd# make install
CDPATH="${ZSH_VERSION+.}:" && cd . && aclocal-1.13
/bin/bash: aclocal-1.13: command not found
Makefile:339: recipe for target 'aclocal.m4' failed
make: **\* [aclocal.m4] Error 127

**Comment by litespeedtech** [comment]
run fixtimestamp.sh should avoid using autoconf again. updated the instruction.
