### ISSUE TITLE
Benefits over Memcached?

### ISSUE THREAD

**Issue by binaryfire** [litespeedtech/lsmcd#17]
Hi guys

Sorry to post a question here, but I haven't been able to find the answer. Just wondering if there are still any benefits to using LSMCD over regular Memcached, now that Memcached supports SASL? (https://github.com/memcached/memcached/wiki/SASLHowto). 

It's for a shared hosting environment running OLS.

Also, is current version of LSMCD based on version 1.6.x of Memcached?

Thanks!

**Comment by rperper** [comment]
Yes, actually there is.  It's an issue of security.  With our SASL support there are a couple of additional features:
- Secure user data.  This means that data saved by one user is not visible to any other users. 
- Anonymous user.  To support the use of code that does not include authentication information (old code or code which wishes to use the facility but does not wish to deal with authentication), you can allow unauthenticated (anonymous) users to create and access data on your server that is distinct and separate from that created by authenticated users.

These features are mentioned here: https://docs.litespeedtech.com/products/lsmcd/configuration/sasl/

Thanks,

Bob Perper

**Comment by rperper** [comment]
Oh, as to the version it's based on, it's somewhat older than 1.6 but the exact version, I don't know.
Thanks,

Bob

**Comment by binaryfire** [comment]
@rperper Hey Bob. I didn't realise secure user data was separate feature to the auth. Good to know, thanks!
