### ISSUE TITLE
Make install error centos7

### ISSUE THREAD

**Issue by rkhoury82** [litespeedtech/lsmcd#3]
Hi there,

I downloaded from master branch and ran:
cd lsmcd
./configure
make install

got the following error. Seems to be a file missing? expat.h ? 

Any advice? 

ake[3]: Entering directory `/lsmcd/src/util'
g++ -DHAVE_CONFIG_H -I. -I../../src -I../../include -I../../src  -I/usr/include  -g -O2 -fstack-protector   -MT xmlnode.o -MD -MP -MF .deps/xmlnode.Tpo -c -o xmlnode.o xmlnode.cpp
xmlnode.cpp:13:19: fatal error: expat.h: No such file or directory
 #include <expat.h>
                   ^
compilation terminated.
make[3]: *** [xmlnode.o] Error 1
make[3]: Leaving directory `/lsmcd/src/util'
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory `/lsmcd/src/util'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/lsmcd/src'
make: *** [install-recursive] Error 1

**Comment by Code-Egg** [comment]
Hi,

**Comment by rkhoury82** [comment]
Cheers that fixed it
