### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by aiso-net** [litespeedtech/lsmcd#30]
When trying to update on CL7 to the latest version of lsmcd (we have a previous older version installed and was running fine), after make and install trying to start the updated service gives me the error:

Jan 11 07:21:29 XXXXX lsmcd[572485]: _sasl_plugin_load failed on sasl_auxprop_plug_init for plugin: sql
Jan 11 07:21:29 XXXXX lsmcd[572485]: auxpropfunc error invalid parameter supplied
Jan 11 07:21:29 XXXXX lsmcd[572485]: _sasl_plugin_load failed on sasl_auxprop_plug_init for plugin: ldapdb
Jan 11 07:21:29 XXXXX lsmcd[572485]: ldapdb_canonuser_plug_init() failed in sasl_canonuser_add_plugin(): invalid parameter supplied
Jan 11 07:21:29 XXXXX  lsmcd[572485]: _sasl_plugin_load failed on sasl_canonuser_init for plugin: ldapdb
Jan 11 07:21:30 XXXXX  lsmcd[572467]: start lsmcd                                 [        ERROR        ]
Jan 11 07:21:30 XXXXX  systemd[1]: lsmcd.service: control process exited, code=exited status=255
Jan 11 07:21:30 XXXXX  systemd[1]: Failed to start LSB: lsmcd.
Jan 11 07:21:30 XXXXX  systemd[1]: Unit lsmcd.service entered failed state.

How can I fix this?

**Comment by rperper** [comment]
This is actually not a compile error, it's a loading error.  It's caused by unnecessary and incorrectly configured plugins.  Check out: https://docs.litespeedtech.com/products/lsmcd/troubleshooting/#unrelated-messages-in-the-system-journal-when-lsmcd-starts-up  If you uninstall a number of unnecessary plugins like `cyrus-sasl-sql` and `cyrus-sasl-ldap` you should no longer get these messages.

Thanks,

Bob

**Comment by aiso-net** [comment]
Thanks, I did yum remove cyrus-sasl-ntlm cyrus-sasl-sql cyrus-sasl-ldap and it still fails to start:

[root@XXXXX lsmcd-master]# systemctl start lsmcd
Job for lsmcd.service failed because the control process exited with error code. See "systemctl status lsmcd.service" and "journalctl -xe" for details.
[root@XXXXX  lsmcd-master]# systemctl status lsmcd.service
â lsmcd.service - LSB: lsmcd
   Loaded: loaded (/etc/rc.d/init.d/lsmcd; bad; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2023-01-11 07:30:46 PST; 2s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 583545 ExecStart=/etc/rc.d/init.d/lsmcd start (code=exited, status=255)
   CGroup: /system.slice/lsmcd.service
           ââ   1307 ./bin/lsmcd -f /usr/local/lsmcd/conf/node.conf
           ââ   1322 ./bin/lsmcd
           ââ2825855 ./bin/lsmcd
           ââ2825856 ./bin/lsmcd
           ââ2825857 ./bin/lsmcd
           ââ2825858 ./bin/lsmcd

Jan 11 07:30:44 XXXXX  systemd[1]: Starting LSB: lsmcd...
Jan 11 07:30:46 XXXXX  lsmcd[583545]: start lsmcd                                 [        ERROR        ]
Jan 11 07:30:46 XXXXX  systemd[1]: lsmcd.service: control process exited, code=exited status=255
Jan 11 07:30:46 XXXXX  systemd[1]: Failed to start LSB: lsmcd.
Jan 11 07:30:46 XXXXX  systemd[1]: Unit lsmcd.service entered failed state.
Jan 11 07:30:46 XXXXX  systemd[1]: lsmcd.service failed.

**Comment by rperper** [comment]
systemd may not see it, but the daemon may still be there.  Please do a `ps-ef|grep lsmcd` and see if the daemon is still there.  Does it service requests?

Thanks,

Bob

**Comment by aiso-net** [comment]
Thanks, we can close this, your correct it was running some how already...and I bookmarked that troubleshooting page in my notes.

[root@XXXXXX lsmcd-master]# ps -ef|grep lsmcd
root        1307       1  0  2022 ?        00:08:19 ./bin/lsmcd -f /usr/local/lsmcd/conf/node.conf
nobody      1322    1307  0  2022 ?        00:10:59 ./bin/lsmcd
root      587249  527778  0 07:37 pts/0    00:00:00 grep --color=auto lsmcd
nobody   2825855    1307  0  2022 ?        00:32:12 ./bin/lsmcd
nobody   2825856    1307  0  2022 ?        01:26:41 ./bin/lsmcd
nobody   2825857    1307  0  2022 ?        00:54:48 ./bin/lsmcd
nobody   2825858    1307  0  2022 ?        00:25:24 ./bin/lsmcd
[root@XXXXXX lsmcd-master]# killall lsmcd
[root@XXXXXX lsmcd-master]# ps -ef|grep lsmcd
root      587300  527778  0 07:37 pts/0    00:00:00 grep --color=auto lsmcd
[root@XXXXXX lsmcd-master]# systemctl start lsmcd
[root@XXXXXX lsmcd-master]#
